import type { Metadata } from "next";
import { Chivo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const chivo = Chivo({
  subsets: ["latin"],
  variable: "--font-chivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", chivo.variable)}>
      <body className={`${chivo.className} antialiased`}>
        <nav className="fixed top-10 left-4 right-4 md:left-1/2 md:right-auto md:-translate-x-1/2 z-50 bg-white/80 backdrop-blur-md px-4 md:px-8 py-3 md:py-4 rounded-full shadow-lg md:w-[calc(100%-4rem)] md:max-w-6xl">
          <div className="flex items-center justify-between">
            <button className="text-sm font-medium text-gray-800 hover:text-blue-600 transition-colors min-w-[60px] md:min-w-[80px]">
              Enlighten
            </button>
            <ul className="hidden md:flex items-center gap-6 lg:gap-8">
              <li>
                <a
                  href="/"
                  className="text-sm font-medium text-gray-800 hover:text-blue-600 transition-colors"
                >
                  Feed
                </a>
              </li>
              <li>
                <a
                  href="/about"
                  className="text-sm font-medium text-gray-800 hover:text-blue-600 transition-colors"
                >
                  Lessons
                </a>
              </li>
              <li>
                <a
                  href="/contact"
                  className="text-sm font-medium text-gray-800 hover:text-blue-600 transition-colors"
                >
                  FAQ
                </a>
              </li>
            </ul>
            <button className="text-sm font-medium bg-blue-600 text-white px-3 md:px-4 py-2 rounded-full hover:bg-blue-700 transition-colors min-w-[60px] md:min-w-[80px]">
              Sign Up
            </button>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
